### ISSUE TITLE
按照你的demo配置，一直报这个异常

### ISSUE THREAD

**Issue by liuhw1988** [abel533/MyBatis-Spring-Boot#104]
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.base.BaseSelectProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseSelectProvider] with root cause

java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.base.BaseSelectProvider.<init>()

**Comment by abel533** [comment]
配置mapper的代码发一下，启动类的注解也发一下。

**Comment by liuhw1988** [comment]
不好意思哈，我发现启动类的注解MapperScan导错包了，导成了org.mybatis.spring.annotation.MapperScan，换成tk.mybatis.spring.annotation.MapperScan就没问题了
