### ISSUE TITLE
项目启动总是报这个错，这是什么原因

### ISSUE THREAD

**Issue by chenyi2333** [abel533/MyBatis-Spring-Boot#105]
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-01-26 16:25:39 1516955139000 [restartedMain] ERROR o.s.b.d.LoggingFailureAnalysisReporter:42 - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target tk.mybatis.mapper.autoconfigure.MapperProperties@7a2f61e5 failed:

    Property: mapper.mappers
    Value: tk.mybatis.springboot.util.MyMapper
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.util.List' for property 'mappers'; nested exception is java.lang.IllegalArgumentException: Cannot find class [tk.mybatis.springboot.util.MyMapper]

Action:

Update your application's configuration

**Comment by chenyi2333** [comment]
这个是因为我配的Druid配置有问题的原因吗

**Comment by happyxiaodou** [comment]
pagehelper:
   helper-dialect: "mysql"
   reasonable: "true"
   support-methods-arguments: "true"
   params: "count=countSql"

以字符串的形式配置就好了
