### ISSUE TITLE
insertList报错，版本1.2.0

### ISSUE THREAD

**Issue by hyygavin1990** [abel533/MyBatis-Spring-Boot#106]
具体调用
    @RequestMapping(value = "/add")
    public String add() {
        List<City> cities = new ArrayList<>();
        City city1 = new City();
        city1.setName("aaaa");
        city1.setState("aaaa1");
        City city2 = new City();
        city2.setName("aaaa");
        city2.setState("aaaa1");
        City city3 = new City();
        city3.setName("aaaa");
        city3.setState("aaaa1");
        cities.add(city1);
        cities.add(city2);
        cities.add(city3);
        cityService.insert(cities);
        return "success";
    }

public void insert(List<City> cities) {
        cityDao.insertList(cities);
    }

java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.SpecialProvider.<init>()

配置如下
# 设置激活的环境
spring.profiles.active=dev
# mybatis 配置
mybatis.type-aliases-package=cn.datawin.model
mybatis.mapper-locations=classpath:mapper/*.xml
# 通用 Mapper 配置
mapper.mappers=cn.datawin.util.Mapper
mapper.not-empty=false
mapper.identity=MYSQL
# 分页插件配置
pagehelper.helperDialect=mysql
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql

**Comment by abel533** [comment]
用 1.2.3

**Comment by unloserv** [comment]
我也遇到这个问题了
1.2.1没有这个问题,但是由于实体中使用了java8的LocalDateTime等字段,用1.2.1使用insert不能自动识别这些字段
改用1.2.3,然后就出现了insertList()后报错
`Error invoking SqlProvider method (tk.mybatis.mapper.provider.SpecialProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.SpecialProvider`
然后受以为大哥的启发,弃用在application.yam中配置改用java配置,经测试后未发现问题
配置类代码如下
`package com.cn.canghuang.blog.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import tk.mybatis.spring.mapper.MapperScannerConfigurer;

import java.util.Properties;

/**
 * tk.mybatis 通用mapper配置类
 *
 * Created by unloserv on 2018/2/27.
 */
@Configuration
public class TkMybatisConfig {

    /**
     *  等同于
     *  Application.java中的注解 @MapperScan(BasePackage = "com.cn.canghuang.blog.mapper")
     *  和 application.yml中的配置
         mapper:
             mappers:
                - com.cn.canghuang.blog.util.MyMapper
             not-empty: false
             identity: MYSQL
     * 注意, 此处的MapperScannerConfigurer为tk.mybatis自带,并非由org.mybatis提供
     * @return
     */
    @Bean(name = "callConfigurer")
    public static MapperScannerConfigurer mapperScannerConfigurer(){
        MapperScannerConfigurer mapperScannerConfigurer = new MapperScannerConfigurer();
        //自定义mapper(dao)位置
        mapperScannerConfigurer.setBasePackage("com.cn.canghuang.blog.mapper");
        Properties propertiesMapper = new Properties();
        //通用mapper位置，不要和其他mapper、dao放在同一个目录
        propertiesMapper.setProperty("mappers", "com.cn.canghuang.blog.util.MyMapper");
        propertiesMapper.setProperty("notEmpty", "false");
        propertiesMapper.setProperty("identity", "MYSQL");
        mapperScannerConfigurer.setProperties(propertiesMapper);
        mapperScannerConfigurer.setSqlSessionFactoryBeanName("sqlSessionFactory");
        return mapperScannerConfigurer;
    }
}
`

**Comment by abel533** [comment]
@unloserv 这是 1.2.3 的bug导致的（mappers不能生效），换 1.2.4 版本即可！

**Comment by abel533** [comment]
看这儿解决：https://github.com/abel533/Mapper/wiki/faq
