### ISSUE TITLE
问题：事务如何使用？

### ISSUE THREAD

**Issue by LiuXiaoJie** [abel533/MyBatis-Spring-Boot#11]
看到config里面配置了事务，请问这个如何使用？在service层类上加上@Transactional注解好像不起作用，打印的SQL语句提示事务不被spring管理，把@Transactional注解移到mapper层，提示事务被spring管理。请问如何让事务作用在service层？

在[stackoverflow](http://stackoverflow.com/questions/38528436/spring-boot-mybatis-transaction-not-work)上看到相似问题，也没有得到解答。

**Comment by SoberChina** [comment]
配置事物是在你程序执行过程中出现不可预知的异常，比如你配置了数据库的事务，在单独的方法加上@Transaction，这个单独的方法有两个在同时操作数据库，一个是成功的一个是失败的，那么这时候数据库就会执行回滚操作。如果没有配置数据库事务数据不会回滚。

**Comment by helloworldtang** [comment]
如果所有事务处理策略都相同，然后写了n多一样的@Transactional（xxx），好麻烦啊
