### ISSUE TITLE
如何实现自定义enum 类型转换

### ISSUE THREAD

**Issue by springCkWyy** [abel533/MyBatis-Spring-Boot#113]
不清楚通用mapper 是否支持 enum 类型转换， 比如数字是2， 我希望返回体是start， 即enum。 不知道这个应该怎么做？

现在自定义TypeHandler的时候，getNullableResult、getNullableResult等方法 不执行， 无法转换。 报错如下：

nested exception is org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column 'status' from result set. Cause: java.lang.IllegalArgumentException: No enum constant com.StatusEnum.2",

**Comment by abel533** [comment]
这里的文档：https://github.com/abel533/Mapper/wiki/7.2.typehandler
