### ISSUE TITLE
 集成activiti报错

### ISSUE THREAD

**Issue by dpjs** [abel533/MyBatis-Spring-Boot#115]
mapper依赖persistence-api-1.0.jar,现在集成activiti报

APPLICATION FAILED TO START

Description:

Parameter 0 of method transactionManager in org.activiti.spring.boot.JpaProcessEngineAutoConfiguration$JpaConfiguration required a bean of type 'javax.persistence.EntityManagerFactory' that could not be found.

Action:

Consider defining a bean of type 'javax.persistence.EntityManagerFactory' in your configuration. 因为这个jar包导致的报错，请问怎么处理现在

**Comment by abel533** [comment]
排除低版本的（Mapper的这个），换合适版本的。

**Comment by dpjs** [comment]
@abel533 Mapper用的刚发布最新版本

**Comment by abel533** [comment]
@dpjs 和通用Mapper版本无关，是依赖的 jpa 版本和你需要的不一样。

**Comment by qiuzhi** [comment]
我也遇到了这个问题，有更详细的解决方案吗？@abel533

**Comment by qiuzhi** [comment]
好了，排掉persistence-api即可
