### ISSUE TITLE
如何获取自增主键

### ISSUE THREAD

**Issue by shidongzhou** [abel533/MyBatis-Spring-Boot#118]
请教前辈，在springboot+mybatis项目中，使用通用Mapper的insertSelective()方法，如何来获取自增主键ID？

**Comment by abel533** [comment]
先看文档主键策略。

insert 后，直接 调用对象的 getId() 方法。

**Comment by shidongzhou** [comment]
项目中用到的mapper-spring-boot-starter.version是1.1.5，mybatis-spring-boot-starter.version是1.3.1。配置如图
![default](https://user-images.githubusercontent.com/26264553/38065798-adf50878-3337-11e8-838d-740d51540743.png)
![default](https://user-images.githubusercontent.com/26264553/38065822-c9f3e4fe-3337-11e8-92b8-044576ee3728.png)
![default](https://user-images.githubusercontent.com/26264553/38065843-e115f1fe-3337-11e8-8b66-f04f198693f4.png)
![default](https://user-images.githubusercontent.com/26264553/38065856-ee38b128-3337-11e8-9bf7-2371595e9370.png)
getId后还是null，主键策略看过了，如果Mysql的数据库，设置的自增，一直获取不到

**Comment by shidongzhou** [comment]
我在service层对Mapper的一些常用方法进行了封装，方便我在control层的使用，如图：
![default](https://user-images.githubusercontent.com/26264553/38065950-551e4092-3338-11e8-95ec-fafdea048193.png)
![default](https://user-images.githubusercontent.com/26264553/38065970-66597d90-3338-11e8-82bf-c35fdd0ba28d.png)
，如果我升级版本，会给我提示我封装的service异常
![default](https://user-images.githubusercontent.com/26264553/38066179-772fceb6-3339-11e8-8533-c7115fdb4690.png)
，请教前辈是在保持原版本的情况下，该怎么配置

**Comment by shidongzhou** [comment]
前辈，刚我写了个demo，使用同样的框架和配置，在实体上配置@GeneratedValue(strategy = GenerationType.IDENTITY,generator="JDBC")后使用insert方法时可以获取到自增id的，demo与我的框架区别在于我的项目中使用了dubbo，在web中对product进行了服务的调用。会不会是因为dubbo的原因，在insert结束返回数据时自增ID获取不到？
@abel533

**Comment by abel533** [comment]
mapper-starter 换 2.0.1

**Comment by skythinking** [comment]
我也遇到同样的问题,请问你们是怎么解决的@shidongzhou  @abel533
