### ISSUE TITLE
how can i integration spring boot mybatis with pagehelper

### ISSUE THREAD

**Issue by chengbaobao630** [abel533/MyBatis-Spring-Boot#12]
when i use pagehelper and annotation Sqlprovider

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'providerTakesParameterObject' in 'class org.apache.ibatis.builder.annotation.ProviderSqlSource'

i find field providerTakesParameterObject in class PageProviderSqlSource ,but not in use

**Comment by abel533** [comment]
Before mybatis 3.3.1, SqlProvider has `providerTakesParameterObject`.

After mybatis 3.4.0, SqlProvider remove `providerTakesParameterObject`, and add a new field named providerMethodArgumentNames.
```java
try {
    //先针对3.3.1和之前版本做判断
    this.providerTakesParameterObject = (Boolean) metaObject.getValue("providerTakesParameterObject");
} catch (ReflectionException e) {
    //3.4.0+版本，解决#102 by Ian Lim
    providerMethodArgumentNames = (String[]) metaObject.getValue("providerMethodArgumentNames");
}
```

In PageSqlProviderSqlSource, use providerTakesParameterObject to recognition mybatis version, and run different createSqlSource method.
```java
private SqlSource createSqlSource(Object parameterObject) {
    if(providerTakesParameterObject != null){
        return createSqlSource331(parameterObject);
    } else {
        return createSqlSource340(parameterObject);
    }
}
```

**Comment by abel533** [comment]
what version of mybatis  do you use?

**Comment by chengbaobao630** [comment]
3.4.0

**Comment by chengbaobao630** [comment]
i have fixed it after upgrade my pagehelper version to 4.1.5,thanks.
