### ISSUE TITLE
Springboot配置多数据源后如何能使各数据源都能使用通用mapper？

### ISSUE THREAD

**Issue by Teemoser** [abel533/MyBatis-Spring-Boot#122]
多数据源的DataSource已注入成功，如何在BaseMapper内注入不同的sqlSessionFactory？

**Comment by abel533** [comment]
动态数据源？还是多个独立的sqlsessionfactory?

**Comment by Teemoser** [comment]
动态数据源的，我已经用Spring的AbstractRoutingDataSource注入成功了，谢谢！

**Comment by xkcoding** [comment]
@Teemoser 您好，多数据源的可以给个思路吗？
