### ISSUE TITLE
无法使用@GeneratedValue(generator="UUID")

### ISSUE THREAD

**Issue by Vampx** [abel533/MyBatis-Spring-Boot#124]
Error creating bean with name 'menuMapper' defined in file [C:\Users\Administrator\git\springbootadmin\target\classes\com\px\mapper\console\MenuMapper.class]: Invocation of init method failed; nested exception is tk.mybatis.mapper.MapperException: tk.mybatis.mapper.MapperException: tk.mybatis.mapper.MapperException: menuId - 该字段@GeneratedValue配置只允许以下几种形式:
1.全部数据库通用的@GeneratedValue(generator="UUID")
2.useGeneratedKeys的@GeneratedValue(generator=\"JDBC\")  
3.类似mysql数据库的@GeneratedValue(strategy=GenerationType.IDENTITY[,generator="Mysql"])

配置文件如下
mybatis.type-aliases-package=com.px.model
mybatis.mapper-locations=classpath:mapper/*.xml

mapper.mappers=com.px.util.CustomerMapper
mapper.not-empty=false
mapper.identity=MYSQL

pagehelper.helperDialect=mysql
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql

**Comment by Vampx** [comment]
<dependency>
			<groupId>org.mybatis.spring.boot</groupId>
			<artifactId>mybatis-spring-boot-starter</artifactId>
            <version>1.3.1</version>
			
		</dependency>
		
        <dependency>
            <groupId>tk.mybatis</groupId>
            <artifactId>mapper-spring-boot-starter</artifactId>
            <version>2.0.1</version>
        </dependency>
        
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.2.4</version>
            <exclusions>
                <exclusion>
                    <groupId>org.mybatis.spring.boot</groupId>
                    <artifactId>mybatis-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by Vampx** [comment]
<dependency>
    <groupId>org.mybatis.spring.boot</groupId>
    <artifactId>mybatis-spring-boot-starter</artifactId>
    <version>1.3.1</version>
</dependency>

<dependency>
    <groupId>tk.mybatis</groupId>
    <artifactId>mapper-spring-boot-starter</artifactId>
    <version>1.2.4</version>
</dependency>

<dependency>
    <groupId>com.github.pagehelper</groupId>
    <artifactId>pagehelper-spring-boot-starter</artifactId>
    <version>1.2.3</version>
</dependency> 

这样则可以

**Comment by superZhouDaLu** [comment]
### springboot 版本: 2.0.3.RELEASE
### mapper-spring-boot-starter 版本: 2.0.3-beta1
### pagehelper-spring-boot-starter 版本: 1.2.5

遇到了相同的问题,将主键设置为@GeneratedValue(generator="UUID") 项目启动报错;
解决方式: 将@GeneratedValue(generator="UUID") 改为 
@GeneratedValue(strategy = GenerationType.IDENTITY,generator = "select replace(uuid(),'-','')") ;
### 注意: 还需要修改配置文件
       application.yml内需要在mapper属性新增
                              before: true
                              ORDER: BEFORE

       application.xml内需要在mapper属性新增
                              mapper.before=true
                              mapper.ORDER=BEFORE

**Comment by abel533** [comment]
新版本去掉了UUID方式，改成了需要自己实现的GenId方式（可回写）。

参考文档：https://github.com/abel533/Mapper/wiki/2.5-genId
