### ISSUE TITLE
Bean property 'mapperHelper' is not writable or has an invalid setter method

### ISSUE THREAD

**Issue by longfeizheng** [abel533/MyBatis-Spring-Boot#13]
`NotWritablePropertyException: Invalid property 'mapperHelper' of bean class [org.mybatis.spring.mapper.MapperFactoryBean]: Bean property 'mapperHelper' is not writable or has an invalid setter method`
gradle 搭建提示这个错误，哪里出问题啦？

**Comment by abel533** [comment]
看不出来哪儿的错。

**Comment by longfeizheng** [comment]
这下知道了，因为添加了
`compile 'org.springframework.boot:spring-boot-devtools:1.4.0.RELEASE`

**Comment by tietang** [comment]
这个问题发生在使用Tk MapperScannerConfigurer 时，和mybatis原生的注解和xml方式共存是出现

**Comment by tietang** [comment]
修改tk.mybatis.spring.mapper.MapperScannerConfigurer中的postProcessBeanDefinitionRegistry方法，卸载原来的beandefinition，重新注册修改后的beandefinition，添加如下代码即可：

```
definition.setBeanClass(MapperFactoryBean.class);
definition.getPropertyValues().add("mapperHelper", this.mapperHelper);
registry.removeBeanDefinition(name);
registry.registerBeanDefinition(name, definition);

```

**Comment by abel533** [comment]
@tietang 这个修改和什么版本有关吗？

**Comment by tietang** [comment]
spring 4.3.x 和spring boot 1.4.x 下集成最新的mybatis-spring-boot, 并集成mapper

**Comment by abel533** [comment]
本项目已经修改，原理参考：[Spring Boot - 配置排序依赖技巧](http://blog.csdn.net/isea533/article/details/53975720)

**Comment by XiaoKang87** [comment]
请问下为什么这么改就好了呢？

**Comment by abel533** [comment]
@XiaoKang87 这是因为有些注解是在starter规范中才启作用，可以看上面原理。

**Comment by wushihua** [comment]
我自己定义了MapperScannerConfigurer就报错了，删掉就可以了，不知道什么问题
