### ISSUE TITLE
使用通用的mapper 中的insertUseGeneratedKeys方法始终拿不到返回的主键？

### ISSUE THREAD

**Issue by ernestfei-zhou** [abel533/MyBatis-Spring-Boot#134]
我在使用通用的mapper 中的insertUseGeneratedKeys方法始终拿不到返回的主键，得到的实体类中的自增主键一直未null,始终拿不到？是怎么回事？基本的错误我都已经排查过了。我用的是mysql数据库，大神能否给出一些拿不到主键的原因？

**Comment by abel533** [comment]
这个方法要求主键名字是 `id`。

**Comment by ernestfei-zhou** [comment]
好的，大神，感觉活跃度不够高呀！
