### ISSUE TITLE
tk.mybatis使用自定义查询时候查询结果字段缺失

### ISSUE THREAD

**Issue by Abandoner** [abel533/MyBatis-Spring-Boot#136]
在使用tk.mybatis的时候遇到了字段缺失的问题, 继承到的selectByPrimaryKey(Object o)等方法都是正常使用的. 但是自定义的方法查询出来的结果只能对应上实体类中没有下划线的字段,其他的字段都查询不到.
请问这种情况怎么处理

**Comment by abel533** [comment]
驼峰需要自己手动映射，或者开启mybatis自动映射驼峰。
