### ISSUE TITLE
为什么eclipse 克隆下来是空心Java

### ISSUE THREAD

**Issue by 961132897** [abel533/MyBatis-Spring-Boot#139]
为什么eclipse 克隆下来是空心Java

**Comment by abel533** [comment]
先克隆，在按maven导入。

**Comment by 961132897** [comment]
老哥，能不能加我QQ帮下我，我弄了一天了。。就是克隆下来都是空心的。。。555

**Comment by 961132897** [comment]
QQ 961132897

**Comment by 961132897** [comment]
感激不尽有偿帮助，恳请教主出手相救，都是同道中人，理应互相帮助。。救人一命胜造七级浮屠

**Comment by 961132897** [comment]
![11](https://user-images.githubusercontent.com/20620091/42484648-997ef18e-8426-11e8-8637-016abf5e3af4.png)

**Comment by abel533** [comment]
用这个链接下载 zip：https://github.com/abel533/MyBatis-Spring-Boot/archive/master.zip

解压后，按 Maven 导入。

**Comment by 961132897** [comment]
Thank you !  Best Regards Shun.Chen

**Comment by learnCmy** [comment]
您好。请问这个对postgreSql支持吗。mapper.identity=？应该填什么

**Comment by abel533** [comment]
@learnCmy 建议用 jdbc 方式。
