### ISSUE TITLE
使用文档中说明配置, tk.mybatis.springboot.util.MyMapper没有依赖

### ISSUE THREAD

**Issue by apa7** [abel533/MyBatis-Spring-Boot#148]
tk.mybatis.springboot.util.MyMappermapper.mappers=tk.mybatis.springboot.util.MyMapper
jar包是有引入的 
去看source里面也没有, 是不是依赖过来的仓库里面的包就不对?
        <dependency>
            <groupId>tk.mybatis</groupId>
            <artifactId>mapper-spring-boot-starter</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>tk.mybatis</groupId>
            <artifactId>mapper-spring-boot</artifactId>
            <version>2.1.0</version>
            <type>pom</type>
        </dependency>
        
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.2.3</version>
        </dependency>

**Comment by fishitit** [comment]
在generatorConfiguration里修改一下就可以了。
      
<plugin type="tk.mybatis.mapper.generator.MapperPlugin">
            <property name="mappers" value="tk.mybatis.mapper.common.Mapper"/>
        </plugin>
