### ISSUE TITLE
通用mapper配 typehandler好像没什么用

### ISSUE THREAD

**Issue by ChenYilei2016** [abel533/MyBatis-Spring-Boot#153]
properties 中 mybatis.type-handlers-package=xxx

@MappedJdbcTypes({JdbcType.VARCHAR})
@MappedTypes({String.class})
public class MyTypeHandler extends BaseTypeHandler<String> {
    @Override
    public void setNonNullParameter(PreparedStatement ps, int i, String parameter, JdbcType jdbcType) throws SQLException {
        ps.setString(i,"prefix_"+parameter);
    }
使用mapper 接口的操作没有作用~ 自己加的就优

**Comment by pengxianggui** [comment]
没结论就关了？
