### ISSUE TITLE
升级版2.0.0及以上报异常Caused by: java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.base.BaseInsertProvider.<init>()。并且@tk.mybatis.spring.annotation.MapperScan("com.sinosoft.**.domain")

### ISSUE THREAD

**Issue by 835897420** [abel533/MyBatis-Spring-Boot#159]
1: 通用mapper报Caused by: java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.base.BaseInsertProvider.<init>() 异常

2:<dependency>
            <groupId>tk.mybatis</groupId>
            <artifactId>mapper-spring-boot-starter</artifactId>
            <version>2.0.0</version>
        </dependency>

3: @SpringBootApplication
@ComponentScan(basePackages = {"com.sinosoft.*"})
@tk.mybatis.spring.annotation.MapperScan("com.sinosoft.**.domain")
@EnableTransactionManagement
@EnableWebMvc
@EnableScheduling
@EnableAsync
public class MyApplication {
    public static void main(String[] args) {
        SpringApplication.run(MyApplication.class, args);
    }
}

4但是版本切换到2.0.0以下的版本.   就不报错正常了.   而且 @com.mybatis.spring.annotation.MapperScan("com.sinosoft.**.domain")  不带tk
大家有没有遇到这种情况指点一二.  :

**Comment by 835897420** [comment]
@tk.mybatis.spring.annotation.MapperScan 已经改了还是报错。

**Comment by abel533** [comment]
mappers 参数配置问题。
