### ISSUE TITLE
BaseResultMap怎么生成了两份

### ISSUE THREAD

**Issue by yinwq** [abel533/MyBatis-Spring-Boot#160]
![image](https://user-images.githubusercontent.com/15242029/63866872-8571ce80-c9e6-11e9-962f-4c7ff1935926.png)

**Comment by yinwq** [comment]
``<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.yinwq.mapper.ExtProductMapper">
  <resultMap id="BaseResultMap" type="com.yinwq.entity.ExtProduct">
    
    <id column="ID" jdbcType="BIGINT" property="id" />
    <result column="PRODUCT_NAME" jdbcType="VARCHAR" property="productName" />
    <result column="PROVIDER_ID" jdbcType="VARCHAR" property="providerId" />
    <result column="PRODUCT_SCHEME" jdbcType="VARCHAR" property="productScheme" />
    <result column="PRODUCT_CONTENT" jdbcType="VARCHAR" property="productContent" />
    <result column="GUARANTEE_ID" jdbcType="INTEGER" property="guaranteeId" />
    <result column="SCHEME_DETAIL" jdbcType="VARCHAR" property="schemeDetail" />
    <result column="PRODUCT_STATUS" jdbcType="TINYINT" property="productStatus" />
    <result column="PRODUCT_COST" jdbcType="DECIMAL" property="productCost" />
    <result column="NEW_CAR_SALE_PRICE" jdbcType="DECIMAL" property="newCarSalePrice" />
    <result column="USED_CAR_COST_PRICE" jdbcType="DECIMAL" property="usedCarCostPrice" />
    <result column="USED_CAR_SALE_PRICE" jdbcType="DECIMAL" property="usedCarSalePrice" />
    <result column="USER_ID" jdbcType="BIGINT" property="userId" />
    <result column="ORG_ID" jdbcType="BIGINT" property="orgId" />
    <result column="ORG_CODE" jdbcType="VARCHAR" property="orgCode" />
    <result column="CREATE_TIME" jdbcType="TIMESTAMP" property="createTime" />
    <result column="UPDATE_TIME" jdbcType="TIMESTAMP" property="updateTime" />
    <result column="CREATE_PERSON" jdbcType="VARCHAR" property="createPerson" />
    <result column="UPDATE_PERSON" jdbcType="VARCHAR" property="updatePerson" />
  </resultMap>
  <resultMap id="BaseResultMap" type="com.yinwq.entity.ExtProduct">
    
    <result column="id" jdbcType="BIGINT" property="id" />
    <result column="product_name" jdbcType="VARCHAR" property="productName" />
    <result column="product_price" jdbcType="DECIMAL" property="productPrice" />
    <result column="provider_id" jdbcType="VARCHAR" property="providerId" />
    <result column="product_content" jdbcType="VARCHAR" property="productContent" />
    <result column="product_scheme" jdbcType="VARCHAR" property="productScheme" />
    <result column="scheme_detail" jdbcType="VARCHAR" property="schemeDetail" />
    <result column="product_status" jdbcType="BIT" property="productStatus" />
    <result column="guarantee_id" jdbcType="INTEGER" property="guaranteeId" />
    <result column="user_id" jdbcType="BIGINT" property="userId" />
    <result column="org_id" jdbcType="BIGINT" property="orgId" />
    <result column="org_code" jdbcType="VARCHAR" property="orgCode" />
    <result column="create_time" jdbcType="TIMESTAMP" property="createTime" />
    <result column="update_time" jdbcType="TIMESTAMP" property="updateTime" />
    <result column="create_person" jdbcType="VARCHAR" property="createPerson" />
    <result column="update_person" jdbcType="VARCHAR" property="updatePerson" />
  </resultMap>
</mapper>

**Comment by kailaisi** [comment]
点击了两次生成mapper吧
