### ISSUE TITLE
insertList抛异常

### ISSUE THREAD

**Issue by maobole** [abel533/MyBatis-Spring-Boot#25]
非常感谢做了这么一个强的工具！

集成到Spring Boot中非常顺利，绝大部分功能都正常，目前遇到一个问题，当批量插入的时候，调insertList方法，会抛出异常：

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.SpecialProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.SpecialProvider
Caused by: java.lang.InstantiationException: tk.mybatis.mapper.provider.SpecialProvider
	at java.lang.Class.newInstance(Class.java:427) ~[na:1.8.0_92]
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:85) ~[mybatis-3.4.0.jar:3.4.0]
	... 82 common frames omitted
Caused by: java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.SpecialProvider.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_92]
	at java.lang.Class.newInstance(Class.java:412) ~[na:1.8.0_92]
	... 83 common frames omitted

集成配置如下：
Pom文件
        <dependency>
            <groupId>tk.mybatis</groupId>
            <artifactId>mapper-spring-boot-starter</artifactId>
            <version>1.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.1.0</version>
        </dependency>

醒置文件：
mapper:
    mappers:
        - com.ld.utils.LordarMapper
    not-empty: false
    identity: MYSQL

类定义：
public interface LordarMapper<T> extends Mapper<T>, MySqlMapper<T> {

}

**Comment by abel533** [comment]
注意看文档中的 mappers 属性，配置成你的 LordarMapper 。

**Comment by maobole** [comment]
谢谢回复，配置文件中已经配了mappers为我自己定义的LordarMapper。。。
![image](https://cloud.githubusercontent.com/assets/1608731/23535126/692dcf64-fff7-11e6-8431-12fe96c2105c.png)

**Comment by Geek-Chic** [comment]
错误是在ProviderSqlSource里的createSqlSource方法
 sql = (String) providerMethod.invoke(providerType.newInstance(), parameterObject);
这里通过反射调用类SpecialProvider，但是SpecialProvider没有空的构造函数，只有一个带参的
 public SpecialProvider(Class<?> mapperClass, MapperHelper mapperHelper) {
        super(mapperClass, mapperHelper);
    }
所以providerType.newInstance()这里会报错？
该如何解决？

**Comment by abel533** [comment]
@Geek-Chic 正常情况下执行不到ProviderSqlsource里面的代码。

错误的原因就是 mappers 配置不对，导致通用方法没有被初始化。

**Comment by luger1990** [comment]
哈哈哈 刚好遇到这个问题了  也是这个错误 我自己写了个通用Mapper 也在查原因

**Comment by luger1990** [comment]
@abel533 我的解决了  我把自定义的Mapper直接放到了业务的Mapper上  没有被初始化  后来放到通用Mapper那个类上就好了 其实这个自定义Mapper不想被所有业务类用的 先这样吧

**Comment by Geek-Chic** [comment]
@abel533 确实是mappers 配置不对的问题，已解决。

**Comment by frankzhiwen** [comment]
@abel533 针对这个InsertList 的 java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.SpecialProvider.() 错误，是否可以给出一个清晰一点的解决思路，看了一下issue 大致懂了，没有找到具体的解决方案

**Comment by abel533** [comment]
如果没有被通用Mapper初始化，就会创建 provider，由于provider不符合要求就会报错。

正常解决问题被初始化，就不会创建Provider了。

**Comment by ssqyht** [comment]
我通过debug 发现  因为没有配置

mapper:
  mappers: com.*.BaseDao
所以下面的代码会执行else分支，默认加载Mapper不会加载自己的com.*.BaseDao
if(this.properties.getMappers().size() > 0) {
            var2 = this.properties.getMappers().iterator();

            while(var2.hasNext()) {
                Class sqlSessionFactory = (Class)var2.next();
                this.applicationContext.getBeansOfType(sqlSessionFactory);
                mapperHelper.registerMapper(sqlSessionFactory);
            }
        } else {
            this.applicationContext.getBeansOfType(Mapper.class);
            mapperHelper.registerMapper(Mapper.class);
        }

**Comment by hyygavin1990** [comment]
大神们  到底怎么解决的啊 能不能说清楚点啊

**Comment by hyygavin1990** [comment]
@abel533

**Comment by hyygavin1990** [comment]
@Geek-Chic @luger1990

**Comment by hyygavin1990** [comment]
@maobole

**Comment by dubinhong** [comment]
Caused by: java.lang.InstantiationException: tk.mybatis.mapper.provider.SpecialProvider
	at java.lang.Class.newInstance(Class.java:427)
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:72)
	... 57 more
批量插入时候报这个错 ，看解决办法都是mappers没有配正确，问一下大神怎么具体配啊   给个详细点的解决办法

**Comment by abel533** [comment]
spring boot 是 mapper.mappers=xxx.YourBaseMapper
其他方式的属性文件为 mappers=xxx.YourBaseMapper

**Comment by yarnping** [comment]
@Mapper
public interface SomeBusinessMapper extends MySqlMapper<Some> {}

//这样调用会报同样的错，不能这样用吗
businessMapper.insertList(list);

version:
`<dependency>
	<groupId>tk.mybatis</groupId>
	<artifactId>mapper-spring-boot-starter</artifactId>
	<version>1.2.4</version>
</dependency>
`

**Comment by liuguangjun** [comment]
我遇到的情况是引入注解包@MapperScan错误也报这个错
　　正确是：import tk.mybatis.spring.annotation.MapperScan;
　　错误的：import org.mybatis.spring.annotation.MapperScan;
