### ISSUE TITLE
com.jinkai.entity.AuthUser cannot be cast to com.jinkai.entity.AuthUser

### ISSUE THREAD

**Issue by jinkai1994** [abel533/MyBatis-Spring-Boot#26]
insert之类的都没问题

但是返回实体对象的时候就会报这个错

具体代码是这样的：
        AuthUser authUser = new AuthUser();
        authUser.setId(1);
        AuthUser auth = authUserDao.selectOne(authUser);

**Comment by workcheng** [comment]
https://github.com/abel533/MyBatis-Spring-Boot/issues/5

**Comment by jinkai1994** [comment]
是这个问题，thank
