### ISSUE TITLE
spirng boot example查询异常

### ISSUE THREAD

**Issue by libsgh** [abel533/MyBatis-Spring-Boot#27]
只有example查询报错，java.lang.RuntimeException: 无法获取实体类cxxx对应的表名!问题滞留了好几天，调试的时候getEntityTable方法中的entityTableMap，的values是空，可能是什么原因导致的？

**Comment by libsgh** [comment]
您好，已经发现问题，由于使用了devtool导致，试着配置：using-boot-devtools-customizing-classload，比较复杂并未成功，希望能给出具体的排除实体包的配置例子，3Q

**Comment by abel533** [comment]
排除条件苛刻，去掉devtools吧。

2017-03-02 19:43 GMT+08:00 libsgh <notifications@github.com>:
