### ISSUE TITLE
java.lang.ClassCastException: com.aaa.user cannot be cast to com.aaa.user

### ISSUE THREAD

**Issue by QiuMing** [abel533/MyBatis-Spring-Boot#31]
参考楼主的配置，但是在用 selectOne 的时候遇到这个错误，一直找不到原因，还希望给点提示

**Comment by QiuMing** [comment]
好吧，找到问题了，是因为我依赖了pring-boot-devtools 。。
之前遇到过几次，时间久了，久忘记这问题了，建议楼主在readme  里面添加下说明，通用 mapper  会和 devtools 有冲突。。。相信后面还会有很多人踩这个坑。。

**Comment by 156248605** [comment]
刚踩了这个坑

**Comment by QiuMing** [comment]
估计掉进坑里面的人会越来多，群主啊，在readme.md 提一下吧，需要发个 pr  给你嘛，此坑不填，估计后人会络绎不绝的掉进来。

**Comment by workcheng** [comment]
README简介有提到
