### ISSUE TITLE
java.lang.ClassCastException: tk.mybatis.springboot.model.PayProductCategory cannot be cast to tk.mybatis.springboot.model.PayProductCategory

### ISSUE THREAD

**Issue by pi408637535** [abel533/MyBatis-Spring-Boot#39]
PayProductCategory payProductCategorySelect = new PayProductCategory();
        payProductCategorySelect.setState((byte)ShopConstants.State.LIVE.ordinal());
        List<PayProductCategory> payProductCategoryList = payProductCategoryMapper.select(payProductCategorySelect);
        for(PayProductCategory payProductCategory : payProductCategoryList){
            System.out.println(payProductCategory);
        }

@Table(name = "pay_product_category")
public class PayProductCategory {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * 父目录.Id=0表一级目录
     */
    @Column(name = "parent_id")
    private Long parentId;

    /**
     * 类目名
     */
    private String name;

    /**
     * 1 正常 0删除
     */
    private Byte state;

    /**
     * 同级目录排序
     */
    @Column(name = "sort_order")
    private Byte sortOrder;

    /**
     * 1代表是父目录 0不是
     */
    @Column(name = "is_parent")
    private Byte isParent;

    @Column(name = "sys_create_time")
    private Date sysCreateTime;

    @Column(name = "sys_update_time")
    private Date sysUpdateTime;
}

我就做着这些操作，为什么会出现类转换异常呢

ava.lang.ClassCastException: tk.mybatis.springboot.model.PayProductCategory cannot be cast to tk.mybatis.springboot.model.PayProductCategory
	at tk.mybatis.springboot.service.front.impl.PayProductServiceImpl.selectAllPayproduct(PayProductServiceImpl.java:31)

**Comment by pi408637535** [comment]
我把进行了打印，发现同样实例的两个类，尽然类加载器不一样。 这个该怎么解决
![image](https://cloud.githubusercontent.com/assets/8135650/25660902/dc9a6d3a-3040-11e7-859a-dffe0448240b.png)

**Comment by abel533** [comment]
Spring DevTools 配置
https://github.com/abel533/Mapper
