### ISSUE TITLE
日志打印问题

### ISSUE THREAD

**Issue by pi408637535** [abel533/MyBatis-Spring-Boot#40]
你好，我使用slf4j进行日志打印。
这个是logback-spring.xml中的部分配置
 <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>${CONSOLE_LOG_PATTERN}</pattern>
            <charset>utf8</charset>
        </encoder>
    </appender>

    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <encoder>
            <pattern>${FILE_LOG_PATTERN}</pattern>
        </encoder>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${LOG_FILE}.%d{yyyy-MM-dd}.log</fileNamePattern>
            <maxHistory>40</maxHistory>
        </rollingPolicy>
    </appender>
这个是application.yum中的配置
logging:
    level: INFO

我好奇的是，在编译器中可以正常打印日志，但是将项目移到服务器上时，日志文件中没有任何一条日志记录，这个是和整合的项目有管吗。（我用纯的mybatis+spring boot时，这么配置日志文件是有记录的）

**Comment by helloworldtang** [comment]
没有看到logger节点的配置。

粘个完整的logback-spring.xml看看

**Comment by abel533** [comment]
`application.yum` 后缀错了，yml

**Comment by pi408637535** [comment]
application.yml
server:
    port: ${port}
    context-path: #/liuzh/


druid:
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true


#spring:
#    mvc:
#        view:
#            prefix: /templates/
#            suffix: .ftl
#    freemarker:
#        cache: false
#        request-context-attribute: request
#
#logging:
#    level: INFO

mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


logback-spring.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="true">
    <conversionRule conversionWord="clr" converterClass="org.springframework.boot.logging.logback.ColorConverter" />
    <conversionRule conversionWord="wex" converterClass="org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter" />
    <conversionRule conversionWord="wEx" converterClass="org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter" />

    <property name="CONSOLE_LOG_PATTERN" value="%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"/>
    <property name="FILE_LOG_PATTERN" value="%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"/>

    <property name="LOG_FILE" value="${LOG_FILE:-${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}/}kapac-pay.log}"/>
    <appender name="DEBUG_LEVEL_REMAPPER" class="org.springframework.boot.logging.logback.LevelRemappingAppender">
        <destinationLogger>org.springframework.boot</destinationLogger>
    </appender>

    
    
    <logger name="org.apache.catalina.startup.DigesterFactory" level="ERROR"/>
    <logger name="org.apache.catalina.util.LifecycleBase" level="ERROR"/>
    <logger name="org.apache.coyote.http11.Http11NioProtocol" level="WARN"/>
    <logger name="org.apache.sshd.common.util.SecurityUtils" level="WARN"/>
    <logger name="org.apache.tomcat.util.net.NioSelectorPool" level="WARN"/>
    <logger name="org.crsh.plugin" level="WARN"/>
    <logger name="org.crsh.ssh" level="WARN"/>
    <logger name="org.eclipse.jetty.util.component.AbstractLifeCycle" level="ERROR"/>
    <logger name="org.hibernate.validator.internal.util.Version" level="WARN"/>
    <logger name="org.springframework.boot.actuate.autoconfigure.CrshAutoConfiguration" level="WARN"/>
    <logger name="org.springframework.boot.actuate.endpoint.jmx" additivity="false">
        <appender-ref ref="DEBUG_LEVEL_REMAPPER"/>
    </logger>
    <logger name="org.thymeleaf" additivity="false">
        <appender-ref ref="DEBUG_LEVEL_REMAPPER"/>
    </logger>

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>${CONSOLE_LOG_PATTERN}</pattern>
            <charset>utf8</charset>
        </encoder>
    </appender>

    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <encoder>
            <pattern>${FILE_LOG_PATTERN}</pattern>
        </encoder>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${LOG_FILE}.%d{yyyy-MM-dd}.log</fileNamePattern>
            <maxHistory>40</maxHistory>
        </rollingPolicy>
      
    </appender>

    <root level="INFO">
        <appender-ref ref="${logback.appender}" />
    </root>
</configuration>

**Comment by abel533** [comment]
解决了？

**Comment by helloworldtang** [comment]
怎么sout打印的东西，也打印到日志文件中呢

**Comment by abel533** [comment]
@helloworldtang 没法打印到日志文件，建议直接用日志方式输出。

**Comment by helloworldtang** [comment]
@abel533 第三方包中有不少是使用sout打印的。
譬如ali oss

使用ali的东西多了，发现代码质量也是参差不齐

**Comment by abel533** [comment]
@helloworldtang 重定向即可：https://stackoverflow.com/questions/3228427/redirect-system-out-println

**Comment by helloworldtang** [comment]
@abel533  已解决
[sysout-over-slf4j](http://projects.lidalia.org.uk/sysout-over-slf4j/index.html)
