### ISSUE TITLE
多数据源配置

### ISSUE THREAD

**Issue by zhanghaichang** [abel533/MyBatis-Spring-Boot#45]
这边有多数据源的配置么？

**Comment by aprilfish** [comment]
同问，配置多数据源后，分页插件不生效

**Comment by abel533** [comment]
用Spring的动态数据源是最简单的方式。。

如果要配置多少sqlsessionfactory，使用starter会自动配置分页插件。

@aprilfish 你是如何配置的？

**Comment by aprilfish** [comment]
不好意思刚看到，spring-boot用pagehelper-spring-boot-starter这个依赖就解决了，开始代码是用spring mvc项目中复制过来的，引用的依赖不对
