### ISSUE TITLE
打包成jar包后运行出错，出现EmptyProvider缺少selectOne方法，这是为何？

### ISSUE THREAD

**Issue by zw231212** [abel533/MyBatis-Spring-Boot#52]
Caused by: tk.mybatis.mapper.MapperException: tk.mybatis.mapper.provider.EmptyPr
ovider中缺少selectOne方法!

我的使用idea来打包，在project structure中设置artifacts，添加jar包输出。

**Comment by abel533** [comment]
你有自己的通用方法？或者发一个你有问题的Mapper接口看看。

**Comment by zw231212** [comment]
我是直接什么都没改的，直接pull项目后拿到idea里面运行是正常，但是按照上面的打包方式去打包，就会出现缺少方法这样的错误。
后面我使用mvn package来打包——jar，这样就能运行，应该是打包的方式的问题。
我那样的打包方式不知道问题在哪里，还在查找原因中（打包方式就是：在artifacts里面选择jar包，然后选择from modules，选择main方法，然后选择copy output to dictinary，选择META-INF/MANIFEST.MF文件的位置，点击确定，这样就好了（为了防止一个目录上的jar包太多，所以把jar包都放到了新建的lib目录下，然后修改classpath，在每个jar包前面，增加lib目录），最后apply，然后到Build->build artifacts ，然后运行jar包）。
结果：项目本身没问题，使用idea运行，使用mvn来打包也没问题。
