### ISSUE TITLE
Spring-Boot多数据源引用出错

### ISSUE THREAD

**Issue by zxh2013** [abel533/MyBatis-Spring-Boot#59]
com.github.pagehelper.autoconfigure.MapperAutoConfiguration required a single bean, but 2 were found:
- ***SqlSessionFactory: defined by method '***SqlSessionFactory' in class path resource [MyBatisConfig.class]
	- sqlSessionFactoryMain: defined in class path resource [***-database.xml]
Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

求解答。

**Comment by abel533** [comment]
用的什么版本？

**Comment by zxh2013** [comment]
SpringBoot：1.5.4.RELEASE
pagehelper：5.0.3
pagehelper-spring-boot-starter：1.1.2

**Comment by zxh2013** [comment]
解决了，在session注入的时候加上了Primary标签，优先其他session注入。
