### ISSUE TITLE
如何查看自动生成的 mapper.xml 文件内容?

### ISSUE THREAD

**Issue by lmovse** [abel533/MyBatis-Spring-Boot#62]
很感谢开发出这么好用的工具，让我的工作量瞬间少了很多，整体项目也变得更为简洁。我有尝试过在程序运行过程去获取自动生成的 mapper sql 语句内容，可是在 classes 文件或者源码目录都不存在，这个是动态生成的吗？用完即销毁？期待您的回答，

**Comment by abel533** [comment]
动态生成的，都在内存中。
