### ISSUE TITLE
insert(model)方法,某些情况不返回自增主键值

### ISSUE THREAD

**Issue by liunewshine** [abel533/MyBatis-Spring-Boot#71]
![image](https://user-images.githubusercontent.com/7698511/30192203-b5cc82fa-9478-11e7-959d-32b172936bdc.png)
如果id为null,正常返回主键值
如果id为0,则主键值返回0
![image](https://user-images.githubusercontent.com/7698511/30192236-ef16ccb4-9478-11e7-89ed-e56f3089c46a.png)
但是在mysql里面,不论id是否为0都返回正常主键值

**Comment by abel533** [comment]
你主键策略配置对了吗？

**Comment by liunewshine** [comment]
![image](https://user-images.githubusercontent.com/7698511/30237297-a678d7f6-9561-11e7-86a5-27bbc9199056.png)
 正确的

**Comment by abel533** [comment]
IDENTITY参数配置了吗？

**Comment by liunewshine** [comment]
IDENTITY的参数指啥？

**Comment by liunewshine** [comment]
指id的值吗？id的值如果设为null就是正确的，设置为0就无法正常返回主键

**Comment by abel533** [comment]
https://mapperhelper.github.io/docs/2.use/

在上面页面搜就行。。

id不能有默认值，否则会使用默认值作为主键插入。

你直接在数据库执行也是这种效果。

**Comment by liunewshine** [comment]
我在数据库直接执行，id赋值为0，是可以正常返回主键值的
https://user-images.githubusercontent.com/7698511/30192236-ef16ccb4-9478-11e7-89ed-e56f3089c46a.png

**Comment by abel533** [comment]
0 可能会特殊处理，Mapper也是把0传过去。。但是没有执行取值操作。

**Comment by liunewshine** [comment]
好的，那如果前台传了0我就手动设置为null
