### ISSUE TITLE
使用Example方法扔报错

### ISSUE THREAD

**Issue by shidongzhou** [abel533/MyBatis-Spring-Boot#82]
你好，前辈，在你的博客上下载的最新代码，
![default](https://user-images.githubusercontent.com/26264553/32358275-c0dd4c64-c07f-11e7-8ba4-c20bf003450b.png)
仍然有org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'distinct' in 'class tk.mybatis.springboot.model.UserInfo'
这个错误，

**Comment by shidongzhou** [comment]
@abel533

**Comment by abel533** [comment]
注意所有 Example 相关方法的参数都是 Example 类型。

**Comment by shidongzhou** [comment]
你好前辈，问题已解决了，还是自己的查询参数有问题.........

**Comment by liuguichuan666** [comment]
nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'distinct' in 'class tk.mybatis.mapper.entity.Example$Criteria'  , 我也报了这种错误，我是想在city里也用cityMapper.selectByExample(criteria);  这是什么情况啊

**Comment by shidongzhou** [comment]
Example 相关方法的参数都是 Example 类型。要注意类型的转换，这样写试试

public List<Product> getInfoByExample(String productName, byte productType) {
		Example example = new Example(Product.class);
		Example.Criteria criteria = example.createCriteria();
		//你的条件参数
		criteria.andEqualTo("productName", productName);
		criteria.andEqualTo("productType", productType);
		List<Product> proList = productMapper.selectByExample(example);
		logger.info("根据Example获取 {}", proList);
		return proList;
	}

**Comment by liuguichuan666** [comment]
额，是我写错了，我传的是criteria，谢谢啦
