### ISSUE TITLE
跟activiti集成会报错

### ISSUE THREAD

**Issue by kings1990** [abel533/MyBatis-Spring-Boot#87]
加了依赖：
<dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-spring-boot-starter-basic</artifactId>
            <version>6.0.0</version>
        </dependency>
集成activiti 
错误如下：org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'javax.persistence.EntityManagerFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by kings1990** [comment]
手动切换数据源解决

**Comment by hgkmail** [comment]
遇到同样的问题，能详细描述一下解决方法吗

**Comment by qiuzhi** [comment]
@kings1990 最后怎样处理呢？
